on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

name: Upload Release

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    name: Upload Release

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
	  id: build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
	- name: Create Release
	  id: create_release
	  uses: actions/create-release@v1
	  env:
	    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
    - name: Upload Release Asset
	  id: upload_release_asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/debug/contact-backend
          asset_name: target/debug/contact-backend
          asset_content_type: application/x-elf


